### PR TITLE
Used WindowOrWorkerGlobalScope instead of GlobalFetch

### LINKED ISSUE #23: TypeScript 3.6.2 removed GlobalFetch
Similar issue: https://github.com/apollographql/apollo-link/issues/1131

Wamp wump. I can fix this too. 😅

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
Fixes #23

### CODE REVIEW

**Comment by quisido** [comment]
Interesting. Is this backwards compatible with older versions of TypeScript, or a breaking change requiring a TSC upgrade for consumers?

**Comment by JoshuaKGoldberg** [comment]
@CharlesStover it was added in TypeScript 3.0. So you could consider that a breaking change. https://github.com/DefinitelyTyped/DefinitelyTyped/issues/40050

Alternately, this code snippet is backwards compatible by allowing either or both to already exist:

```ts
interface GlobalFetch { }
interface WindowOrWorkerGlobalScope { }
interface GlobalFetchOrWindowOrWorkerGlobalScope extends GlobalFetch, WindowOrWorkerGlobalScope { }

type CreateUseFetch = (fetch: GlobalFetchOrWindowOrWorkerGlobalScope['fetch']) => UseFetch;
```

This PR is set to allow edits from maintainers, if that snippet makes sense to you. 😄

**Comment by quisido** [comment]
Interesting. The snippet makes sense to me [and it works in the TypeScript playground](http://www.typescriptlang.org/play/#code/JYOwLgpgTgZghgYwgAgOIBsD2AjO6BiEYCAFsgN7IC+AUKJLIigOqgAmmA7gPJTOZQA1tAw48AZQSYADikq160eEjRZcBIqV6sQHHnwHCoo9ZJkoIAD0i6AzqrEbiJADTIde7YZFqJU2RTUNDRgAJ4BAMJQEHCQAKq2EITOyAC8yAAUMJokAFwO6slafOxcXkI+jmayANoA5NnOdQC6AJRpAHzIIACu6OgA3DRAA) for 3.1.6+, but Travis CI fails to build with this definition.

In 3.0.1, you receive:
```
Interface 'GlobalFetchOrWindowOrWorkerGlobalScope' cannot simultaneously extend types 'GlobalFetch' and 'WindowOrWorkerGlobalScope'.
  Named property 'fetch' of types 'GlobalFetch' and 'WindowOrWorkerGlobalScope' are not identical.
```

I'll try a custom implementation and see if that resolves it.

**Comment by quisido** [comment]
Ugh. So code that compiles in TypeScript Playground will not compile here. It's likely due to how old this TypeScript compiler is. I think I am fine with just upgrading the TypeScript version to get this to work, but I don't want to spam more commits into your PR. Would you want to trial-and-error the TypeScript versions and see if you can build it locally (`yarn build` or `npm run build`)?

**Comment by JoshuaKGoldberg** [comment]
Yeah that's a tricky one. I noticed you already use `window.fetch` down in the exports, so this should do the trick instead:

```ts
type FetchFunction = typeof window.fetch;
```

Added in 98baabc.

Alternately, `typeof fetch` would work too.

**Comment by quisido** [comment]
Very smooth solution, thank you. :)

**Pull request merged**
