### PR TITLE
Update response headers check

### PR DESCRIPTION
**Pull request by dan-kez**
Presently I always receive a text response rather than JSON.

It doesn't look like the check is doing what it's intended to do. Happy to make further changes if necessary!

### CODE REVIEW

**Comment by quisido** [comment]
I'll be out until Sunday. I'll try to get this merged by Monday at the latest. If I forget it, please tag me. :)

**Comment by chihuama** [comment]
@CharlesStover I'm also interested in this fix. Thanks!

**Comment by quisido** [comment]
Thank you for pinging me on this. I'll get it in today.

**Comment by quisido** [comment]
I've merged this and changed it to  `response.headers.get('Content-Type') && (indexOf check)`, as I was getting `null` when the Content-Type isn't sent, which would cause `.indexOf` to throw an error.

1.0.2 should be published soon with this change. If you encounter errors, please report, as I didn't test this. 😄

**Pull request merged**
