### PR TITLE
Make `fetch` configurable via `options.client`

### PR DESCRIPTION
**Pull request by tomchentw**
Hi, thanks for the great lib! I'm new to TS so please forgive my newbie typings.

I personally use the composable **fetch** lib called [http-client](https://www.npmjs.com/package/http-client). This PR allows me to use the `fetch` it generated instead of defaulting to the global one.

```js
import useFetch from "fetch-suspense";
import { createFetch } from "http-client";

const client = createFetch(/* … */);

useFetch(input, init, {
  client,
});
```

### CODE REVIEW

**Comment by tomchentw** [comment]
@CharlesStover let me know if there's anything I can do to merge this, thanks!

**Comment by quisido** [comment]
Sorry for the late response. When I get these in my email, GitHub removes the notification, and I forget to reply when I'm on a desktop and can actually read the code.

I like the idea of configurable fetches and supporting them, but I'm just not sure if adding an options parameter is the way to do it. It might be, I'm just not fully convinced and don't want to push a breaking change if it ends up going another way in the future.

Is there a reason you don't want to override the global fetch with your created one?

**Comment by tomchentw** [comment]
> not sure if adding an options parameter is the way to do it

@CharlesStover I do agree. I would be better to create a factory of `useFetch` function, but I just failed to figure out the right signature for it. lol

> Is there a reason you don't want to override the global fetch with your created one?

Good question. Custom fetch may include various pre-configured headers & options, which make it only limit to specific cases. For example,

```js
const fetch = createFetch(
  base('https://api.stripe.com/v1'),  // Prefix all request URLs
  accept('application/json'),         // Set "Accept: application/json" in the request headers
  parse('json')                       // Read the response as JSON and put it in response.body
)
```

If I override it to the global fetch, then I have no other way to create a `accept: text` fetch request in the future.

**Comment by quisido** [comment]
I like the factory idea.

```JavaScript
export const createUseFetch = fetch => { /* ... */ };
export default createUseFetch(global.fetch);
```

I'll open an issue for it, but unfortunately releasing the newest ReactN will come before I can implement this.

**Comment by tomchentw** [comment]
Thanks! I'll see if I can figure out a PR :)

**Pull request closed without merging**
